### ISSUE TITLE
Compatibility with Jetson TK1

### ISSUE THREAD

**Issue by m2coyote** [alfonsosanchezbeato/jetson-ubuntu-core#1]
Hello
Thanks for this useful repo
I want to ask if it is possible to port Ubuntu Core on Jetson TK1?
Can I use the tarball of TX1 to flash the TK1?

Thanks in advance

**Comment by alfonsosanchezbeato** [comment]
@m2coyote, no, I do not think the TX1 tarball will work with the TK1. The problem with porting to the TK1 is that its kernel is quite old, and many apparmor patches would need to be backported to have a proper Ubuntu Core image.
